### ISSUE TITLE
doesn't work in burp 1.7.19 with builtin jre

### ISSUE THREAD

**Issue by kokanin** [nccgroup/Berserko#1]
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at burp.lqb.a(Unknown Source)
	at burp.lqb.<init>(Unknown Source)
	at burp.uqg.a(Unknown Source)
	at burp.xue.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by rtt-ncc** [comment]
Could you provide some further details?
Which version of Berserko? Or is it the 'Kerberos Authentication' extension from the BApp Store?
What OS are you running on?

Just checked and berserko-0.9beta.jar from the Releases tab of this repo loads fine in Burp 1.7.19 with builtin JRE on my Windows x64 box.

**Comment by kokanin** [comment]
berserko-0.9beta.jar, windows 10 x64

**Comment by rtt-ncc** [comment]
I've now tested this on Windows 10 x64 and can't reproduce the issue.
Can you load other Java-based Burp extensions? The exception trace above actually indicates that Burp is failing to load the extension in the first place. Is it possible that your JAR file is corrupted? SHA-256 should be b5db26c2f8d79dea0eea2c181ff5d5f3ceb09bd211ec6d4bf715cc3f095b2909.
